# Created by Yunhai Feng at 2022/5/5

# GAIL single episode v1-4
# pure gail imitation, no task reward (gail_reward_coef = 1.0)
# New: Decrease both learning rates of agent and discriminator
#      GAIL.DISCRIMINATOR.lr = 1e-5
#      RL.PPO.lr = 1e-4
BASE_TASK_CONFIG_PATH: "configs/objectnav_expert_mp3d_single_episode_seed11b.yaml" ###
DEMO_TASK_CONFIG_PATH: "configs/objectnav_expert_mp3d_single_episode_seed11b.yaml" ###
CMD_TRAILING_OPTS: ["TASK_CONFIG.ENVIRONMENT.ITERATOR_OPTIONS.MAX_SCENE_REPEAT_STEPS", "50000"]
TRAINER_NAME: "gail"
ENV_NAME: "NavGAILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
#VIDEO_OPTION: ["disk", "tensorboard"]
VIDEO_OPTION: []
TENSORBOARD_DIR: "/home/fyh/Data/habitat/tb/gail_single_episode_v1_4/seed11b" ###
VIDEO_DIR: "/home/fyh/Data/video_dir/gail_single_episode_v1_4/seed11b" ###
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "/home/fyh/Data/habitat/checkpoints/gail_single_episode_v1_4/seed11b" ###
NUM_ENVIRONMENTS: 2
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
CHECKPOINT_FOLDER: "/home/fyh/Data/habitat/checkpoints/gail_single_episode_v1_4/seed11b" ###
NUM_UPDATES: 100000
LOG_INTERVAL: 10
NUM_CHECKPOINTS: 100
# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

EVAL:
  SPLIT: "val"

RL:
  SUCCESS_REWARD: 2.5
  SLACK_REWARD: -1e-3

  POLICY:
    name: "PointNavResNetPolicy"
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: ("ResizeShortestEdge", "CenterCropper")

  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 1e-4
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 64
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50
    use_normalized_advantage: False

    hidden_size: 512

  DDPPO:
    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: NCCL
    # Visual encoder backbone
    pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
    # Initialize with pretrained weights
    pretrained: False
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: False
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: True
    # Whether or not to reset the critic linear layer
    reset_critic: True

    # Model parameters
    backbone: resnet50
    rnn_type: LSTM
    num_recurrent_layers: 2

GAIL:
  use_double_buffer: True
  gail_reward_coef: 1.0 # 0.5
  is_demonstration_env: False

  DISCRIMINATOR:
    hidden_size: 512
    resnet_baseplanes: 32
    backbone: "resnet50"
    normalize_visual_inputs: False

    discriminator_epoch: 8
    num_mini_batch: 1
    lr: 1e-5
    eps: 1e-5
    use_linear_lr_decay: False
    max_grad_norm: 0.2
